### ISSUE TITLE
Enhanced implementation of request status

### ISSUE THREAD

**Issue by msachi** [lucy-marko/centrepoint#164]
- [x] Show open / closed / in-progress status
- [x] Show other visual cues (e.g. bold text for open request)
- [x] Ability to assign admins (including themselves) to specific request
- [x] Ability to close a request (with 'are you sure' message)
